export const ALL_ISSUE = "ALL_ISSUE";
export const ADD_ISSUE = "ADD_ISSUE";
export const UPDATE_ISSUE = "UPDATE_ISSUE";
export const DELETE_ISSUE = "DELETE_ISSUE";
export const COMPLETE_ISSUE = "COMPLETE_ISSUE";

export const ALL_ISSUE_STATUS_COUNTER = "ALL_ISSUE_STATUS_COUNTER";
export const ADD_ISSUE_STATUS_COUNTER = "ADD_ISSUE_STATUS_COUNTER";
export const UPDATE_ISSUE_STATUS_COUNTER = "UPDATE_ISSUE_STATUS_COUNTER";
export const DELETE_ISSUE_STATUS_COUNTER = "DELETE_ISSUE_STATUS_COUNTER";
